version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/fastapi-app

hooks:
  BeforeInstall:
    - location: scripts/preDeploy.sh
      timeout: 300
      runas: ec2-user

  ApplicationStart:
    - location: scripts/postDeploy.sh
      timeout: 300
      runas: ec2-user

  ValidateService:
    - location: scripts/validate.sh
      timeout: 60
      runas: ec2-user
