version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies into package"
      - pip install --upgrade pip
      - pip install -r requirements.txt -t package/

  build:
    commands:
      - echo "Compiling Python files"
      - python -m compileall package/

  post_build:
    commands:
      - echo "Copying Lambda code"
      - cp main.py package/
      - echo "Zipping Lambda package"
      - cd package
      - zip -r ../lambda_package.zip .
      - cd ..

artifacts:
  files:
    - lambda_package.zip
  discard-paths: yes
