version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "No dependencies to install"

  build:
    commands:
      - echo "Preparing Lambda function"

artifacts:
  files:
    - lambda_function.py