version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "No dependencies to install"

  build:
    commands:
      - echo "Packaging Lambda function"
      - zip -r lambda_package.zip lambda_function.py

artifacts:
  files:
    - lambda_package.zip
