version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "No dependencies to install"

  build:
    commands:
      - echo "Checking Python syntax..."
      - python -m py_compile lambda_function.py
      - echo "Syntax OK, preparing Lambda function"

artifacts:
  files:
    - lambda_function.py
    - appspec.yml
