version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Upgrading pip..."
      - pip install --upgrade pip
      - echo "Installing dependencies into build folder..."
      - pip install -r requirements.txt -t build/

  build:
    commands:
      - echo "Copying Lambda function code..."
      - cp main.py build/
      - echo "Zipping Lambda package..."
      - cd build
      - zip -r ../lambda_package.zip .
      - cd ..

artifacts:
  files:
    - lambda_package.zip
  discard-paths: yes
